"""change users

Revision ID: e2eba39dd0aa
Revises: 2a5a789a7202
Create Date: 2025-03-20 01:21:12.016988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e2eba39dd0aa'
down_revision: Union[str, None] = '2a5a789a7202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('initials', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('coach_initials', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('date', sa.String(length=255), nullable=False))
    op.drop_column('users', 'age')
    op.drop_column('users', 'patronymic')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'coach_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('coach_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('patronymic', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('users', sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'date')
    op.drop_column('users', 'coach_initials')
    op.drop_column('users', 'initials')
    # ### end Alembic commands ###
